"""
Guionbajo — Master Calibrated Diagnosis Question Bank (80 Questions)
60 Curricular Questions (6 progressive level bands x 10 questions)
20 Phonetic Questions (10 Pure Audio Discrimination + 10 Highlighted Word-Phoneme Mapping)
"""
from typing import List, Dict, Any

CURRICULAR_QUESTIONS_60: List[Dict[str, Any]] = [   {   'band': 1,
        'correct_answer': 'is',
        'id': 1,
        'level': 'A1.1',
        'options': ['am', 'is', 'are', 'be'],
        'points': 5,
        'question': 'Complete the sentence: "She _______ from Canada."',
        'section': 'curriculum',
        'topic': 'Verb To Be (Affirmative)',
        'type': 'grammar'},
    {   'band': 1,
        'correct_answer': 'They',
        'id': 2,
        'level': 'A1.1',
        'options': ['Them', 'They', 'He', 'Him'],
        'points': 5,
        'question': 'Choose the correct subject pronoun: "_______ are my best friends."',
        'section': 'curriculum',
        'topic': 'Subject Pronouns',
        'type': 'grammar'},
    {   'band': 1,
        'correct_answer': 'meet',
        'id': 3,
        'level': 'A1.1',
        'options': ['meet', 'meat', 'met', 'meeting'],
        'points': 5,
        'question': 'Select the polite phrase: "Nice to _______ you."',
        'section': 'curriculum',
        'topic': 'Greetings & Introductions',
        'type': 'vocabulary'},
    {   'band': 1,
        'correct_answer': 'an',
        'id': 4,
        'level': 'A1.1',
        'options': ['the', 'an', 'one', 'a'],
        'points': 5,
        'question': 'Choose the correct article: "He is _______ architect in New York."',
        'section': 'curriculum',
        'topic': 'Indefinite Articles (a/an)',
        'type': 'grammar'},
    {   'band': 1,
        'correct_answer': "aren't",
        'id': 5,
        'level': 'A1.2',
        'options': ['am not', "aren't", "isn't", "don't"],
        'points': 5,
        'question': 'Complete: "We _______ at home right now; we are at school."',
        'section': 'curriculum',
        'topic': 'Verb To Be (Negative)',
        'type': 'grammar'},
    {   'band': 1,
        'correct_answer': 'Spanish',
        'id': 6,
        'level': 'A1.2',
        'options': ['Spaniard', 'Spanish', 'Spainer', 'Spain'],
        'points': 5,
        'question': 'Select the correct nationality: "Maria is from Spain. She is _______."',
        'section': 'curriculum',
        'topic': 'Nationalities',
        'type': 'vocabulary'},
    {   'band': 1,
        'correct_answer': 'This',
        'id': 7,
        'level': 'A1.2',
        'options': ['That', 'This', 'These', 'Those'],
        'points': 5,
        'question': 'Look here in my hand: "_______ is my new phone."',
        'section': 'curriculum',
        'topic': 'Demonstratives (This/That)',
        'type': 'grammar'},
    {   'band': 1,
        'correct_answer': 'women',
        'id': 8,
        'level': 'A1.2',
        'options': ['womens', 'woman', 'women', 'womans'],
        'points': 5,
        'question': 'Complete with plural form: "There are three _______ in the meeting room."',
        'section': 'curriculum',
        'topic': 'Irregular Plurals',
        'type': 'grammar'},
    {   'band': 1,
        'correct_answer': 'Is',
        'id': 9,
        'level': 'A1.2',
        'options': ['Is', 'Am', 'Does', 'Are'],
        'points': 5,
        'question': 'Choose the correct question starter: "_______ your brother at the office today?"',
        'section': 'curriculum',
        'topic': 'Questions with To Be',
        'type': 'grammar'},
    {   'band': 1,
        'correct_answer': 'Its',
        'id': 10,
        'level': 'A1.2',
        'options': ['Her', 'His', "It's", 'Its'],
        'points': 5,
        'question': 'Complete the sentence: "I have a cat. _______ name is Whiskers."',
        'section': 'curriculum',
        'topic': 'Possessive Adjectives',
        'type': 'grammar'},
    {   'band': 2,
        'correct_answer': 'wakes',
        'id': 11,
        'level': 'A1.3',
        'options': ['is waking', 'wake', 'waking', 'wakes'],
        'points': 5,
        'question': 'Complete: "Daniel _______ up at 6:30 every morning."',
        'section': 'curriculum',
        'topic': 'Present Simple (3rd person)',
        'type': 'grammar'},
    {   'band': 2,
        'correct_answer': "doesn't",
        'id': 12,
        'level': 'A1.3',
        'options': ["don't", "isn't", 'not', "doesn't"],
        'points': 5,
        'question': 'Select the negative form: "He _______ eat meat because he is a vegetarian."',
        'section': 'curriculum',
        'topic': 'Present Simple (Negative)',
        'type': 'grammar'},
    {   'band': 2,
        'correct_answer': 'Do',
        'id': 13,
        'level': 'A1.3',
        'options': ['Are', 'Do', 'Is', 'Does'],
        'points': 5,
        'question': 'Complete: "_______ your parents live in London?"',
        'section': 'curriculum',
        'topic': 'Questions with Do/Does',
        'type': 'grammar'},
    {   'band': 2,
        'correct_answer': 'at',
        'id': 14,
        'level': 'A1.3',
        'options': ['in', 'on', 'at', 'by'],
        'points': 5,
        'question': 'Choose the correct preposition: "The train departs _______ 8:15 AM."',
        'section': 'curriculum',
        'topic': 'Time Prepositions (at/in/on)',
        'type': 'grammar'},
    {   'band': 2,
        'correct_answer': 'never',
        'id': 15,
        'level': 'A1.3',
        'options': ['sometimes', 'always', 'never', 'usually'],
        'points': 5,
        'question': 'Choose the adverb: "She _______ arrives late for class; she is always punctual."',
        'section': 'curriculum',
        'topic': 'Adverbs of Frequency',
        'type': 'vocabulary'},
    {   'band': 2,
        'correct_answer': 'is crying',
        'id': 16,
        'level': 'A1.4',
        'options': ['cries', 'cry', 'cried', 'is crying'],
        'points': 5,
        'question': 'Action happening now: "Listen! The baby _______ right now."',
        'section': 'curriculum',
        'topic': 'Present Continuous',
        'type': 'grammar'},
    {   'band': 2,
        'correct_answer': 'Is there',
        'id': 17,
        'level': 'A1.4',
        'options': ['Are there', 'There is', 'Is there', 'There are'],
        'points': 5,
        'question': 'Choose the question: "_______ any milk left in the fridge?"',
        'section': 'curriculum',
        'topic': 'There is / There are',
        'type': 'grammar'},
    {   'band': 2,
        'correct_answer': 'can',
        'id': 18,
        'level': 'A1.4',
        'options': ['can', 'cans', 'can to', 'is can'],
        'points': 5,
        'question': 'Complete: "She _______ speak three languages fluently."',
        'section': 'curriculum',
        'topic': 'Modal Can (Ability)',
        'type': 'grammar'},
    {   'band': 2,
        'correct_answer': 'played',
        'id': 19,
        'level': 'A1.4',
        'options': ['playing', 'plaied', 'played', 'play'],
        'points': 5,
        'question': 'Past action: "Yesterday afternoon, we _______ tennis in the park."',
        'section': 'curriculum',
        'topic': 'Past Simple Regular (-ed)',
        'type': 'grammar'},
    {   'band': 2,
        'correct_answer': 'left',
        'id': 20,
        'level': 'A1.4',
        'options': ['leave', 'leaving', 'left', 'leaved'],
        'points': 5,
        'question': 'Complete with irregular past: "Last night I _______ my keys on the table."',
        'section': 'curriculum',
        'topic': 'Past Simple Irregular',
        'type': 'grammar'},
    {   'band': 3,
        'correct_answer': "didn't",
        'id': 21,
        'level': 'A2.1',
        'options': ["didn't", "wasn't", "weren't", "don't"],
        'points': 5,
        'question': 'Complete: "They _______ see the concert yesterday because it was cancelled."',
        'section': 'curriculum',
        'topic': "Past Simple Negative (didn't)",
        'type': 'grammar'},
    {   'band': 3,
        'correct_answer': 'did',
        'id': 22,
        'level': 'A2.1',
        'options': ['did', 'do', 'have', 'were'],
        'points': 5,
        'question': 'Complete: "Where _______ you go on vacation last summer?"',
        'section': 'curriculum',
        'topic': 'Past Simple Question (Did)',
        'type': 'grammar'},
    {   'band': 3,
        'correct_answer': 'was',
        'id': 23,
        'level': 'A2.1',
        'options': ['were', 'been', 'is', 'was'],
        'points': 5,
        'question': 'Complete: "The weather _______ terrible during our entire trip."',
        'section': 'curriculum',
        'topic': 'Was / Were',
        'type': 'grammar'},
    {   'band': 3,
        'correct_answer': 'was writing',
        'id': 24,
        'level': 'A2.1',
        'options': ['am writing', 'wrote', 'was writing', 'was wrote'],
        'points': 5,
        'question': 'Action in progress in the past: "At 9 PM yesterday, I _______ an English essay."',
        'section': 'curriculum',
        'topic': 'Past Continuous',
        'type': 'grammar'},
    {   'band': 3,
        'correct_answer': 'went',
        'id': 25,
        'level': 'A2.1',
        'options': ['were going', 'go', 'went', 'was going'],
        'points': 5,
        'question': 'Combine tenses: "We were cooking dinner when the lights suddenly _______ out."',
        'section': 'curriculum',
        'topic': 'Interrupted Past Actions',
        'type': 'grammar'},
    {   'band': 3,
        'correct_answer': 'faster',
        'id': 26,
        'level': 'A2.2',
        'options': ['fast', 'faster', 'fastest', 'more fast'],
        'points': 5,
        'question': 'Compare: "Travelling by plane is usually _______ than taking the bus."',
        'section': 'curriculum',
        'topic': 'Comparatives (regular)',
        'type': 'grammar'},
    {   'band': 3,
        'correct_answer': 'better',
        'id': 27,
        'level': 'A2.2',
        'options': ['gooder', 'better', 'more good', 'best'],
        'points': 5,
        'question': 'Compare: "My English today is much _______ than it was two years ago."',
        'section': 'curriculum',
        'topic': 'Comparatives (irregular)',
        'type': 'grammar'},
    {   'band': 3,
        'correct_answer': 'highest',
        'id': 28,
        'level': 'A2.2',
        'options': ['high', 'most high', 'higher', 'highest'],
        'points': 5,
        'question': 'Superlative form: "Mount Everest is the _______ mountain in the world."',
        'section': 'curriculum',
        'topic': 'Superlatives',
        'type': 'grammar'},
    {   'band': 3,
        'correct_answer': 'much',
        'id': 29,
        'level': 'A2.2',
        'options': ['much', 'many', 'any', 'few'],
        'points': 5,
        'question': 'Choose the quantifier: "How _______ money do you have in your wallet?"',
        'section': 'curriculum',
        'topic': 'Countable vs Uncountable (much/many)',
        'type': 'grammar'},
    {   'band': 3,
        'correct_answer': 'any',
        'id': 30,
        'level': 'A2.2',
        'options': ['no', 'any', 'many', 'some'],
        'points': 5,
        'question': 'Negative sentence: "We don\'t have _______ sugar to bake the cake."',
        'section': 'curriculum',
        'topic': 'Quantifiers (some/any)',
        'type': 'grammar'},
    {   'band': 4,
        'correct_answer': 'is going to',
        'id': 31,
        'level': 'A2.3',
        'options': ['goes to', 'shall', 'is going to', 'will to'],
        'points': 5,
        'question': 'Look at those dark clouds! "It _______ rain very soon."',
        'section': 'curriculum',
        'topic': 'Future with Going To (Evidence)',
        'type': 'grammar'},
    {   'band': 4,
        'correct_answer': 'will',
        'id': 32,
        'level': 'A2.3',
        'options': ['going to', 'will', 'shall be', 'am going'],
        'points': 5,
        'question': 'Spontaneous promise: "I promise I _______ help you with your project tonight."',
        'section': 'curriculum',
        'topic': 'Future with Will (Promise)',
        'type': 'grammar'},
    {   'band': 4,
        'correct_answer': 'should',
        'id': 33,
        'level': 'A2.3',
        'options': ['would', 'ought', 'should', 'must to'],
        'points': 5,
        'question': 'Giving advice: "You look exhausted. You _______ go to bed early."',
        'section': 'curriculum',
        'topic': 'Modal of Advice (Should)',
        'type': 'grammar'},
    {   'band': 4,
        'correct_answer': 'have to',
        'id': 34,
        'level': 'A2.3',
        'options': ['has to', 'should to', 'have to', 'must to'],
        'points': 5,
        'question': 'Company rule: "In this company, all employees _______ wear an ID badge."',
        'section': 'curriculum',
        'topic': 'Modal of Obligation (Have to)',
        'type': 'grammar'},
    {   'band': 4,
        'correct_answer': 'rains',
        'id': 35,
        'level': 'A2.4',
        'options': ['will rain', 'rained', 'is raining', 'rains'],
        'points': 5,
        'question': 'Conditional condition: "If it _______ tomorrow, we will stay at home."',
        'section': 'curriculum',
        'topic': 'First Conditional (If clause)',
        'type': 'grammar'},
    {   'band': 4,
        'correct_answer': 'will',
        'id': 36,
        'level': 'A2.4',
        'options': ['would', 'are', 'will', 'did'],
        'points': 5,
        'question': 'Result clause: "If you practice every day, you _______ improve quickly."',
        'section': 'curriculum',
        'topic': 'First Conditional (Result clause)',
        'type': 'grammar'},
    {   'band': 4,
        'correct_answer': 'who',
        'id': 37,
        'level': 'A2.4',
        'options': ['who', 'which', 'where', 'whose'],
        'points': 5,
        'question': 'Relative pronoun: "The woman _______ lives next door is a software engineer."',
        'section': 'curriculum',
        'topic': 'Relative Pronouns (People: Who)',
        'type': 'grammar'},
    {   'band': 4,
        'correct_answer': 'which',
        'id': 38,
        'level': 'A2.4',
        'options': ['where', 'whom', 'who', 'which'],
        'points': 5,
        'question': 'Relative pronoun: "This is the laptop _______ I bought yesterday."',
        'section': 'curriculum',
        'topic': 'Relative Pronouns (Objects: Which)',
        'type': 'grammar'},
    {   'band': 4,
        'correct_answer': 'take off',
        'id': 39,
        'level': 'A2.4',
        'options': ['get off', 'give up', 'take off', 'turn off'],
        'points': 5,
        'question': 'Select phrasal verb: "Please _______ your shoes before entering the house."',
        'section': 'curriculum',
        'topic': 'Spatial Phrasal Verbs (Take off)',
        'type': 'vocabulary'},
    {   'band': 4,
        'correct_answer': 'turn on',
        'id': 40,
        'level': 'A2.4',
        'options': ['pick out', 'look for', 'turn up', 'turn on'],
        'points': 5,
        'question': 'Select phrasal verb: "It is very dark in here; can you _______ the lights?"',
        'section': 'curriculum',
        'topic': 'Everyday Phrasal Verbs (Turn on)',
        'type': 'vocabulary'},
    {   'band': 5,
        'correct_answer': 'eaten',
        'id': 41,
        'level': 'B1.1',
        'options': ['eat', 'eaten', 'eating', 'ate'],
        'points': 5,
        'question': 'Life experience: "Have you ever _______ Japanese food?"',
        'section': 'curriculum',
        'topic': 'Present Perfect (Life Experience)',
        'type': 'grammar'},
    {   'band': 5,
        'correct_answer': 'went',
        'id': 42,
        'level': 'B1.1',
        'options': ['go', 'went', 'have been', 'have gone'],
        'points': 5,
        'question': 'Specific past time: "I _______ to London in the summer of 2021."',
        'section': 'curriculum',
        'topic': 'Present Perfect vs Past Simple',
        'type': 'grammar'},
    {   'band': 5,
        'correct_answer': 'for',
        'id': 43,
        'level': 'B1.1',
        'options': ['for', 'since', 'during', 'ago'],
        'points': 5,
        'question': 'Duration: "She has worked as a doctor _______ five years."',
        'section': 'curriculum',
        'topic': 'Duration with For',
        'type': 'grammar'},
    {   'band': 5,
        'correct_answer': 'since',
        'id': 44,
        'level': 'B1.1',
        'options': ['for', 'in', 'since', 'from'],
        'points': 5,
        'question': 'Starting point: "They have lived in this apartment _______ 2018."',
        'section': 'curriculum',
        'topic': 'Starting point with Since',
        'type': 'grammar'},
    {   'band': 5,
        'correct_answer': 'yet',
        'id': 45,
        'level': 'B1.1',
        'options': ['already', 'yet', 'still', 'just'],
        'points': 5,
        'question': 'Negative expectation: "I checked my inbox, but I haven\'t received your email _______."',
        'section': 'curriculum',
        'topic': 'Present Perfect with Yet',
        'type': 'grammar'},
    {   'band': 5,
        'correct_answer': 'would',
        'id': 46,
        'level': 'B1.2',
        'options': ['had', 'would', 'can', 'will'],
        'points': 5,
        'question': 'Hypothetical situation: "If I won a million dollars, I _______ travel around the world."',
        'section': 'curriculum',
        'topic': 'Second Conditional (Hypothetical)',
        'type': 'grammar'},
    {   'band': 5,
        'correct_answer': 'were',
        'id': 47,
        'level': 'B1.2',
        'options': ['were', 'am', 'have been', 'was'],
        'points': 5,
        'question': 'Imaginary state: "If I _______ in your position, I would decline that risky proposal."',
        'section': 'curriculum',
        'topic': 'Second Conditional (Subjunctive Were)',
        'type': 'grammar'},
    {   'band': 5,
        'correct_answer': 'painted',
        'id': 48,
        'level': 'B1.2',
        'options': ['paints', 'painted', 'painting', 'paint'],
        'points': 5,
        'question': 'Passive voice: "That famous masterpiece was _______ by Leonardo da Vinci."',
        'section': 'curriculum',
        'topic': 'Passive Voice (Past Simple)',
        'type': 'grammar'},
    {   'band': 5,
        'correct_answer': 'find out',
        'id': 49,
        'level': 'B1.2',
        'options': ['look up', 'find out', 'give up', 'run out'],
        'points': 5,
        'question': 'Discover information: "We need to _______ what time the flight departs."',
        'section': 'curriculum',
        'topic': 'Cognitive Phrasal Verbs (Find out)',
        'type': 'vocabulary'},
    {   'band': 5,
        'correct_answer': 'In my opinion',
        'id': 50,
        'level': 'B1.2',
        'options': ['For my view', 'In my opinion', 'As to me', 'According to me'],
        'points': 5,
        'question': 'Expressing viewpoint: "_______, remote work increases productivity when managed well."',
        'section': 'curriculum',
        'topic': 'Opinion Linking Expressions',
        'type': 'vocabulary'},
    {   'band': 6,
        'correct_answer': "wouldn't have",
        'id': 51,
        'level': 'B2.1',
        'options': ["hadn't", "won't have", "wouldn't", "wouldn't have"],
        'points': 5,
        'question': 'Past regret: "If we had left ten minutes earlier, we _______ missed the train."',
        'section': 'curriculum',
        'topic': 'Third Conditional (Past Regret)',
        'type': 'grammar'},
    {   'band': 6,
        'correct_answer': 'would be',
        'id': 52,
        'level': 'B2.1',
        'options': ['is', 'will be', 'would have been', 'would be'],
        'points': 5,
        'question': 'Past cause with present effect: "If he had accepted the promotion last year, he _______ in London '
                    'today."',
        'section': 'curriculum',
        'topic': 'Mixed Conditionals',
        'type': 'grammar'},
    {   'band': 6,
        'correct_answer': 'was feeling',
        'id': 53,
        'level': 'B2.1',
        'options': ['was feeling', 'would feel', 'is feeling', 'had felt'],
        'points': 5,
        'question': 'Reported speech: "She told me: \'I am feeling sick.\' → She told me that she _______ sick."',
        'section': 'curriculum',
        'topic': 'Reported Speech (Tense Backshift)',
        'type': 'grammar'},
    {   'band': 6,
        'correct_answer': 'lived',
        'id': 54,
        'level': 'B2.2',
        'options': ['lived', 'did live', 'do live', 'have lived'],
        'points': 5,
        'question': 'Indirect question word order: "The interviewer asked me where I _______ during college."',
        'section': 'curriculum',
        'topic': 'Reported Questions (Word Order)',
        'type': 'grammar'},
    {   'band': 6,
        'correct_answer': 'must have',
        'id': 55,
        'level': 'B2.2',
        'options': ['must have', 'should have', 'would have', 'could'],
        'points': 5,
        'question': 'Logical certainty about the past: "The ground is soaking wet. It _______ rained heavily last '
                    'night."',
        'section': 'curriculum',
        'topic': 'Modals of Past Deduction (Must have)',
        'type': 'grammar'},
    {   'band': 6,
        'correct_answer': "shouldn't have",
        'id': 56,
        'level': 'B2.2',
        'options': ['must not', "couldn't have", "shouldn't have", "wouldn't have"],
        'points': 5,
        'question': 'Criticism/regret: "I feel terrible today. I _______ eaten that entire greasy pizza."',
        'section': 'curriculum',
        'topic': 'Modals of Past Regret (Should have)',
        'type': 'grammar'},
    {   'band': 6,
        'correct_answer': 'Although',
        'id': 57,
        'level': 'B2.3',
        'options': ['Despite', 'In spite of', 'Although', 'However'],
        'points': 5,
        'question': 'Concession clause: "_______ the weather forecast predicted heavy storms, the team went hiking."',
        'section': 'curriculum',
        'topic': 'Concession Clauses (Although)',
        'type': 'grammar'},
    {   'band': 6,
        'correct_answer': 'Despite',
        'id': 58,
        'level': 'B2.3',
        'options': ['Although', 'Whereas', 'Despite', 'Even though'],
        'points': 5,
        'question': 'Preposition of concession: "_______ the immense financial pressure, the startup achieved '
                    'profitability."',
        'section': 'curriculum',
        'topic': 'Concession Prepositions (Despite + Noun)',
        'type': 'grammar'},
    {   'band': 6,
        'correct_answer': 'had paid',
        'id': 59,
        'level': 'B2.4',
        'options': ['paid', 'would pay', 'have paid', 'had paid'],
        'points': 5,
        'question': 'Expressing past regret: "I wish I _______ more attention during yesterday\'s crucial briefing."',
        'section': 'curriculum',
        'topic': 'Wish + Past Perfect (Past Regret)',
        'type': 'grammar'},
    {   'band': 6,
        'correct_answer': 'had we reached',
        'id': 60,
        'level': 'B2.4',
        'options': ['had we reached', 'did we reach', 'have we reached', 'we had reached'],
        'points': 5,
        'question': 'Formal emphatic inversion: "Hardly _______ the airport when the severe gale began."',
        'section': 'curriculum',
        'topic': 'Formal Inversion (Negative Adverbials)',
        'type': 'grammar'}]

PHONETIC_QUESTIONS_20: List[Dict[str, Any]] = [   {   'audio_url': '/audio/phonemes/fricative_th_voiceless.mp3',
        'correct_answer': '/θ/',
        'id': 61,
        'instruction': 'Pulsa el botón de audio para escuchar el fonema aislado.',
        'options': ['/θ/', '/s/', '/f/', '/ð/'],
        'phoneme_symbol': '/θ/',
        'points': 5,
        'question': 'Escucha el sonido del fonema y selecciona el símbolo IPA correspondiente:',
        'section': 'phonetics',
        'type': 'phonetic_sound'},
    {   'audio_url': '/audio/phonemes/fricative_th_voiced.mp3',
        'correct_answer': '/ð/',
        'id': 62,
        'instruction': 'Pulsa el botón de audio para escuchar el fonema aislado.',
        'options': ['/ð/', '/z/', '/θ/', '/d/'],
        'phoneme_symbol': '/ð/',
        'points': 5,
        'question': 'Escucha el sonido del fonema y selecciona el símbolo IPA correspondiente:',
        'section': 'phonetics',
        'type': 'phonetic_sound'},
    {   'audio_url': '/audio/phonemes/vowel_long_i.mp3',
        'correct_answer': '/iː/',
        'id': 63,
        'instruction': 'Pulsa el botón de audio para escuchar la vocal.',
        'options': ['/e/', '/ɪ/', '/iː/', '/eɪ/'],
        'phoneme_symbol': '/iː/',
        'points': 5,
        'question': 'Escucha la vocal larga y selecciona su símbolo IPA:',
        'section': 'phonetics',
        'type': 'phonetic_sound'},
    {   'audio_url': '/audio/phonemes/vowel_short_i.mp3',
        'correct_answer': '/ɪ/',
        'id': 64,
        'instruction': 'Pulsa el botón de audio para escuchar la vocal.',
        'options': ['/ə/', '/iː/', '/ɪ/', '/e/'],
        'phoneme_symbol': '/ɪ/',
        'points': 5,
        'question': 'Escucha la vocal corta y relajada y selecciona su símbolo IPA:',
        'section': 'phonetics',
        'type': 'phonetic_sound'},
    {   'audio_url': '/audio/phonemes/vowel_short_ae.mp3',
        'correct_answer': '/æ/',
        'id': 65,
        'instruction': 'Pulsa el botón de audio para escuchar la vocal.',
        'options': ['/e/', '/ɑː/', '/æ/', '/ʌ/'],
        'phoneme_symbol': '/æ/',
        'points': 5,
        'question': 'Escucha la vocal abierta y selecciona su símbolo IPA:',
        'section': 'phonetics',
        'type': 'phonetic_sound'},
    {   'audio_url': '/audio/phonemes/fricative_sh.mp3',
        'correct_answer': '/ʃ/',
        'id': 66,
        'instruction': 'Pulsa el botón de audio para escuchar la consonante.',
        'options': ['/s/', '/ʃ/', '/ʒ/', '/tʃ/'],
        'phoneme_symbol': '/ʃ/',
        'points': 5,
        'question': 'Escucha la consonante fricativa y selecciona su símbolo IPA:',
        'section': 'phonetics',
        'type': 'phonetic_sound'},
    {   'audio_url': '/audio/phonemes/affricate_ch.mp3',
        'correct_answer': '/tʃ/',
        'id': 67,
        'instruction': 'Pulsa el botón de audio para escuchar la consonante.',
        'options': ['/t/', '/tʃ/', '/ʃ/', '/dʒ/'],
        'phoneme_symbol': '/tʃ/',
        'points': 5,
        'question': 'Escucha la consonante africada y selecciona su símbolo IPA:',
        'section': 'phonetics',
        'type': 'phonetic_sound'},
    {   'audio_url': '/audio/phonemes/affricate_j.mp3',
        'correct_answer': '/dʒ/',
        'id': 68,
        'instruction': 'Pulsa el botón de audio para escuchar la consonante.',
        'options': ['/j/', '/tʃ/', '/ʒ/', '/dʒ/'],
        'phoneme_symbol': '/dʒ/',
        'points': 5,
        'question': 'Escucha la consonante africada sonora y selecciona su símbolo IPA:',
        'section': 'phonetics',
        'type': 'phonetic_sound'},
    {   'audio_url': '/audio/phonemes/nasal_ng.mp3',
        'correct_answer': '/ŋ/',
        'id': 69,
        'instruction': 'Pulsa el botón de audio para escuchar la consonante.',
        'options': ['/g/', '/m/', '/n/', '/ŋ/'],
        'phoneme_symbol': '/ŋ/',
        'points': 5,
        'question': 'Escucha la consonante nasal velar y selecciona su símbolo IPA:',
        'section': 'phonetics',
        'type': 'phonetic_sound'},
    {   'audio_url': '/audio/phonemes/vowel_schwa.mp3',
        'correct_answer': '/ə/',
        'id': 70,
        'instruction': 'Pulsa el botón de audio para escuchar el sonido.',
        'options': ['/ʌ/', '/e/', '/ə/', '/ɜː/'],
        'phoneme_symbol': '/ə/',
        'points': 5,
        'question': 'Escucha el sonido neutro (Schwa) y selecciona su símbolo IPA:',
        'section': 'phonetics',
        'type': 'phonetic_sound'},
    {   'correct_answer': '/θ/',
        'highlight_part': 'th',
        'id': 71,
        'instruction': 'Presiona la palabra para escucharla y observa las letras resaltadas.',
        'options': ['/t/', '/s/', '/ð/', '/θ/'],
        'phoneme_symbol': '/θ/',
        'points': 5,
        'question': "¿Qué sonido fonético IPA representa la sección resaltada en la palabra 'think'?",
        'section': 'phonetics',
        'target_word': 'think',
        'type': 'phonetic_word'},
    {   'correct_answer': '/ð/',
        'highlight_part': 'th',
        'id': 72,
        'instruction': 'Presiona la palabra para escucharla y observa las letras resaltadas.',
        'options': ['/ð/', '/d/', '/z/', '/θ/'],
        'phoneme_symbol': '/ð/',
        'points': 5,
        'question': "¿Qué sonido fonético IPA representa la sección resaltada en la palabra 'this'?",
        'section': 'phonetics',
        'target_word': 'this',
        'type': 'phonetic_word'},
    {   'correct_answer': '/iː/',
        'highlight_part': 'ee',
        'id': 73,
        'instruction': 'Presiona la palabra para escucharla y observa las letras resaltadas.',
        'options': ['/iː/', '/eɪ/', '/e/', '/ɪ/'],
        'phoneme_symbol': '/iː/',
        'points': 5,
        'question': "¿Qué sonido fonético IPA representa la sección resaltada en la palabra 'sheep'?",
        'section': 'phonetics',
        'target_word': 'sheep',
        'type': 'phonetic_word'},
    {   'correct_answer': '/ɪ/',
        'highlight_part': 'i',
        'id': 74,
        'instruction': 'Presiona la palabra para escucharla y observa las letras resaltadas.',
        'options': ['/iː/', '/e/', '/aɪ/', '/ɪ/'],
        'phoneme_symbol': '/ɪ/',
        'points': 5,
        'question': "¿Qué sonido fonético IPA representa la sección resaltada en la palabra 'ship'?",
        'section': 'phonetics',
        'target_word': 'ship',
        'type': 'phonetic_word'},
    {   'correct_answer': '/æ/',
        'highlight_part': 'a',
        'id': 75,
        'instruction': 'Presiona la palabra para escucharla y observa las letras resaltadas.',
        'options': ['/æ/', '/e/', '/ɑː/', '/ʌ/'],
        'phoneme_symbol': '/æ/',
        'points': 5,
        'question': "¿Qué sonido fonético IPA representa la sección resaltada en la palabra 'cat'?",
        'section': 'phonetics',
        'target_word': 'cat',
        'type': 'phonetic_word'},
    {   'correct_answer': '/ʃ/',
        'highlight_part': 'sh',
        'id': 76,
        'instruction': 'Presiona la palabra para escucharla y observa las letras resaltadas.',
        'options': ['/tʃ/', '/ʒ/', '/s/', '/ʃ/'],
        'phoneme_symbol': '/ʃ/',
        'points': 5,
        'question': "¿Qué sonido fonético IPA representa la sección resaltada en la palabra 'shoe'?",
        'section': 'phonetics',
        'target_word': 'shoe',
        'type': 'phonetic_word'},
    {   'correct_answer': '/tʃ/',
        'highlight_part': 'ch',
        'id': 77,
        'instruction': 'Presiona la palabra para escucharla y observa las letras resaltadas.',
        'options': ['/ʃ/', '/tʃ/', '/dʒ/', '/k/'],
        'phoneme_symbol': '/tʃ/',
        'points': 5,
        'question': "¿Qué sonido fonético IPA representa la sección resaltada en la palabra 'chair'?",
        'section': 'phonetics',
        'target_word': 'chair',
        'type': 'phonetic_word'},
    {   'correct_answer': '/ʒ/',
        'highlight_part': 's',
        'id': 78,
        'instruction': 'Presiona la palabra para escucharla y observa las letras resaltadas.',
        'options': ['/ʒ/', '/z/', '/ʃ/', '/dʒ/'],
        'phoneme_symbol': '/ʒ/',
        'points': 5,
        'question': "¿Qué sonido fonético IPA representa la sección resaltada en la palabra 'vision'?",
        'section': 'phonetics',
        'target_word': 'vision',
        'type': 'phonetic_word'},
    {   'correct_answer': '/dʒ/',
        'highlight_part': 'dg',
        'id': 79,
        'instruction': 'Presiona la palabra para escucharla y observa las letras resaltadas.',
        'options': ['/g/', '/j/', '/tʃ/', '/dʒ/'],
        'phoneme_symbol': '/dʒ/',
        'points': 5,
        'question': "¿Qué sonido fonético IPA representa la sección resaltada en la palabra 'judge'?",
        'section': 'phonetics',
        'target_word': 'judge',
        'type': 'phonetic_word'},
    {   'correct_answer': '/ŋ/',
        'highlight_part': 'ng',
        'id': 80,
        'instruction': 'Presiona la palabra para escucharla y observa las letras resaltadas.',
        'options': ['/g/', '/ŋ/', '/n/', '/nk/'],
        'phoneme_symbol': '/ŋ/',
        'points': 5,
        'question': "¿Qué sonido fonético IPA representa la sección resaltada en la palabra 'sing'?",
        'section': 'phonetics',
        'target_word': 'sing',
        'type': 'phonetic_word'}]

def get_all_diagnosis_questions() -> List[Dict[str, Any]]:
    """Return all 80 calibrated questions (60 curricular + 20 phonetic)."""
    return CURRICULAR_QUESTIONS_60 + PHONETIC_QUESTIONS_20
