"""
Guionbajo — Master Calibrated Diagnosis Question Bank (80 Questions)
60 Curricular Questions (6 progressive level bands x 10 questions)
20 Phonetic Questions (10 Pure Audio Discrimination + 10 Highlighted Word-Phoneme Mapping)
"""
from typing import List, Dict, Any

CURRICULAR_QUESTIONS_60: List[Dict[str, Any]] = [
    # ─── BAND 1: A1 INICIAL (Questions 1-10) ──────────────────────────────────
    {
        "id": 1,
        "band": 1,
        "level": "A1.1",
        "section": "curriculum",
        "type": "grammar",
        "topic": "Verb To Be (Affirmative)",
        "question": 'Complete the sentence: "She _______ from Canada."',
        "options": ["is", "am", "are", "be"],
        "correct_answer": "is",
        "points": 5,
    },
    {
        "id": 2,
        "band": 1,
        "level": "A1.1",
        "section": "curriculum",
        "type": "grammar",
        "topic": "Subject Pronouns",
        "question": 'Choose the correct subject pronoun: "_______ are my best friends."',
        "options": ["They", "He", "Him", "Them"],
        "correct_answer": "They",
        "points": 5,
    },
    {
        "id": 3,
        "band": 1,
        "level": "A1.1",
        "section": "curriculum",
        "type": "vocabulary",
        "topic": "Greetings & Introductions",
        "question": 'Select the polite phrase: "Nice to _______ you."',
        "options": ["meet", "meat", "meeting", "met"],
        "correct_answer": "meet",
        "points": 5,
    },
    {
        "id": 4,
        "band": 1,
        "level": "A1.1",
        "section": "curriculum",
        "type": "grammar",
        "topic": "Indefinite Articles (a/an)",
        "question": 'Choose the correct article: "He is _______ architect in New York."',
        "options": ["an", "a", "the", "one"],
        "correct_answer": "an",
        "points": 5,
    },
    {
        "id": 5,
        "band": 1,
        "level": "A1.2",
        "section": "curriculum",
        "type": "grammar",
        "topic": "Verb To Be (Negative)",
        "question": 'Complete: "We _______ at home right now; we are at school."',
        "options": ["aren't", "isn't", "am not", "don't"],
        "correct_answer": "aren't",
        "points": 5,
    },
    {
        "id": 6,
        "band": 1,
        "level": "A1.2",
        "section": "curriculum",
        "type": "vocabulary",
        "topic": "Nationalities",
        "question": 'Select the correct nationality: "Maria is from Spain. She is _______."',
        "options": ["Spanish", "Spain", "Spaniard", "Spainer"],
        "correct_answer": "Spanish",
        "points": 5,
    },
    {
        "id": 7,
        "band": 1,
        "level": "A1.2",
        "section": "curriculum",
        "type": "grammar",
        "topic": "Demonstratives (This/That)",
        "question": 'Look here in my hand: "_______ is my new phone."',
        "options": ["This", "That", "These", "Those"],
        "correct_answer": "This",
        "points": 5,
    },
    {
        "id": 8,
        "band": 1,
        "level": "A1.2",
        "section": "curriculum",
        "type": "grammar",
        "topic": "Irregular Plurals",
        "question": 'Complete with plural form: "There are three _______ in the meeting room."',
        "options": ["women", "womans", "woman", "womens"],
        "correct_answer": "women",
        "points": 5,
    },
    {
        "id": 9,
        "band": 1,
        "level": "A1.2",
        "section": "curriculum",
        "type": "grammar",
        "topic": "Questions with To Be",
        "question": 'Choose the correct question starter: "_______ your brother at the office today?"',
        "options": ["Is", "Are", "Am", "Does"],
        "correct_answer": "Is",
        "points": 5,
    },
    {
        "id": 10,
        "band": 1,
        "level": "A1.2",
        "section": "curriculum",
        "type": "grammar",
        "topic": "Possessive Adjectives",
        "question": 'Complete the sentence: "I have a cat. _______ name is Whiskers."',
        "options": ["Its", "It's", "His", "Her"],
        "correct_answer": "Its",
        "points": 5,
    },

    # ─── BAND 2: A1 CONSOLIDACIÓN (Questions 11-20) ───────────────────────────
    {
        "id": 11,
        "band": 2,
        "level": "A1.3",
        "section": "curriculum",
        "type": "grammar",
        "topic": "Present Simple (3rd person)",
        "question": 'Complete: "Daniel _______ up at 6:30 every morning."',
        "options": ["wakes", "wake", "waking", "is waking"],
        "correct_answer": "wakes",
        "points": 5,
    },
    {
        "id": 12,
        "band": 2,
        "level": "A1.3",
        "section": "curriculum",
        "type": "grammar",
        "topic": "Present Simple (Negative)",
        "question": 'Select the negative form: "He _______ eat meat because he is a vegetarian."',
        "options": ["doesn't", "don't", "isn't", "not"],
        "correct_answer": "doesn't",
        "points": 5,
    },
    {
        "id": 13,
        "band": 2,
        "level": "A1.3",
        "section": "curriculum",
        "type": "grammar",
        "topic": "Questions with Do/Does",
        "question": 'Complete: "_______ your parents live in London?"',
        "options": ["Do", "Does", "Are", "Is"],
        "correct_answer": "Do",
        "points": 5,
    },
    {
        "id": 14,
        "band": 2,
        "level": "A1.3",
        "section": "curriculum",
        "type": "grammar",
        "topic": "Time Prepositions (at/in/on)",
        "question": 'Choose the correct preposition: "The train departs _______ 8:15 AM."',
        "options": ["at", "in", "on", "by"],
        "correct_answer": "at",
        "points": 5,
    },
    {
        "id": 15,
        "band": 2,
        "level": "A1.3",
        "section": "curriculum",
        "type": "vocabulary",
        "topic": "Adverbs of Frequency",
        "question": 'Choose the adverb: "She _______ arrives late for class; she is always punctual."',
        "options": ["never", "always", "sometimes", "usually"],
        "correct_answer": "never",
        "points": 5,
    },
    {
        "id": 16,
        "band": 2,
        "level": "A1.4",
        "section": "curriculum",
        "type": "grammar",
        "topic": "Present Continuous",
        "question": 'Action happening now: "Listen! The baby _______ right now."',
        "options": ["is crying", "cries", "cry", "cried"],
        "correct_answer": "is crying",
        "points": 5,
    },
    {
        "id": 17,
        "band": 2,
        "level": "A1.4",
        "section": "curriculum",
        "type": "grammar",
        "topic": "There is / There are",
        "question": 'Choose the question: "_______ any milk left in the fridge?"',
        "options": ["Is there", "Are there", "There is", "There are"],
        "correct_answer": "Is there",
        "points": 5,
    },
    {
        "id": 18,
        "band": 2,
        "level": "A1.4",
        "section": "curriculum",
        "type": "grammar",
        "topic": "Modal Can (Ability)",
        "question": 'Complete: "She _______ speak three languages fluently."',
        "options": ["can", "cans", "is can", "can to"],
        "correct_answer": "can",
        "points": 5,
    },
    {
        "id": 19,
        "band": 2,
        "level": "A1.4",
        "section": "curriculum",
        "type": "grammar",
        "topic": "Past Simple Regular (-ed)",
        "question": 'Past action: "Yesterday afternoon, we _______ tennis in the park."',
        "options": ["played", "play", "plaied", "playing"],
        "correct_answer": "played",
        "points": 5,
    },
    {
        "id": 20,
        "band": 2,
        "level": "A1.4",
        "section": "curriculum",
        "type": "grammar",
        "topic": "Past Simple Irregular",
        "question": 'Complete with irregular past: "Last night I _______ my keys on the table."',
        "options": ["left", "leave", "leaved", "leaving"],
        "correct_answer": "left",
        "points": 5,
    },

    # ─── BAND 3: A2 INICIAL (Questions 21-30) ──────────────────────────────────
    {
        "id": 21,
        "band": 3,
        "level": "A2.1",
        "section": "curriculum",
        "type": "grammar",
        "topic": "Past Simple Negative (didn't)",
        "question": 'Complete: "They _______ see the concert yesterday because it was cancelled."',
        "options": ["didn't", "don't", "wasn't", "weren't"],
        "correct_answer": "didn't",
        "points": 5,
    },
    {
        "id": 22,
        "band": 3,
        "level": "A2.1",
        "section": "curriculum",
        "type": "grammar",
        "topic": "Past Simple Question (Did)",
        "question": 'Complete: "Where _______ you go on vacation last summer?"',
        "options": ["did", "were", "do", "have"],
        "correct_answer": "did",
        "points": 5,
    },
    {
        "id": 23,
        "band": 3,
        "level": "A2.1",
        "section": "curriculum",
        "type": "grammar",
        "topic": "Was / Were",
        "question": 'Complete: "The weather _______ terrible during our entire trip."',
        "options": ["was", "were", "been", "is"],
        "correct_answer": "was",
        "points": 5,
    },
    {
        "id": 24,
        "band": 3,
        "level": "A2.1",
        "section": "curriculum",
        "type": "grammar",
        "topic": "Past Continuous",
        "question": 'Action in progress in the past: "At 9 PM yesterday, I _______ an English essay."',
        "options": ["was writing", "wrote", "am writing", "was wrote"],
        "correct_answer": "was writing",
        "points": 5,
    },
    {
        "id": 25,
        "band": 3,
        "level": "A2.1",
        "section": "curriculum",
        "type": "grammar",
        "topic": "Interrupted Past Actions",
        "question": 'Combine tenses: "We were cooking dinner when the lights suddenly _______ out."',
        "options": ["went", "was going", "were going", "go"],
        "correct_answer": "went",
        "points": 5,
    },
    {
        "id": 26,
        "band": 3,
        "level": "A2.2",
        "section": "curriculum",
        "type": "grammar",
        "topic": "Comparatives (regular)",
        "question": 'Compare: "Travelling by plane is usually _______ than taking the bus."',
        "options": ["faster", "more fast", "fastest", "fast"],
        "correct_answer": "faster",
        "points": 5,
    },
    {
        "id": 27,
        "band": 3,
        "level": "A2.2",
        "section": "curriculum",
        "type": "grammar",
        "topic": "Comparatives (irregular)",
        "question": 'Compare: "My English today is much _______ than it was two years ago."',
        "options": ["better", "gooder", "more good", "best"],
        "correct_answer": "better",
        "points": 5,
    },
    {
        "id": 28,
        "band": 3,
        "level": "A2.2",
        "section": "curriculum",
        "type": "grammar",
        "topic": "Superlatives",
        "question": 'Superlative form: "Mount Everest is the _______ mountain in the world."',
        "options": ["highest", "most high", "higher", "high"],
        "correct_answer": "highest",
        "points": 5,
    },
    {
        "id": 29,
        "band": 3,
        "level": "A2.2",
        "section": "curriculum",
        "type": "grammar",
        "topic": "Countable vs Uncountable (much/many)",
        "question": 'Choose the quantifier: "How _______ money do you have in your wallet?"',
        "options": ["much", "many", "few", "any"],
        "correct_answer": "much",
        "points": 5,
    },
    {
        "id": 30,
        "band": 3,
        "level": "A2.2",
        "section": "curriculum",
        "type": "grammar",
        "topic": "Quantifiers (some/any)",
        "question": 'Negative sentence: "We don\'t have _______ sugar to bake the cake."',
        "options": ["any", "some", "no", "many"],
        "correct_answer": "any",
        "points": 5,
    },

    # ─── BAND 4: A2 CONSOLIDACIÓN (Questions 31-40) ───────────────────────────
    {
        "id": 31,
        "band": 4,
        "level": "A2.3",
        "section": "curriculum",
        "type": "grammar",
        "topic": "Future with Going To (Evidence)",
        "question": 'Look at those dark clouds! "It _______ rain very soon."',
        "options": ["is going to", "will to", "goes to", "shall"],
        "correct_answer": "is going to",
        "points": 5,
    },
    {
        "id": 32,
        "band": 4,
        "level": "A2.3",
        "section": "curriculum",
        "type": "grammar",
        "topic": "Future with Will (Promise)",
        "question": 'Spontaneous promise: "I promise I _______ help you with your project tonight."',
        "options": ["will", "am going", "going to", "shall be"],
        "correct_answer": "will",
        "points": 5,
    },
    {
        "id": 33,
        "band": 4,
        "level": "A2.3",
        "section": "curriculum",
        "type": "grammar",
        "topic": "Modal of Advice (Should)",
        "question": 'Giving advice: "You look exhausted. You _______ go to bed early."',
        "options": ["should", "must to", "ought", "would"],
        "correct_answer": "should",
        "points": 5,
    },
    {
        "id": 34,
        "band": 4,
        "level": "A2.3",
        "section": "curriculum",
        "type": "grammar",
        "topic": "Modal of Obligation (Have to)",
        "question": 'Company rule: "In this company, all employees _______ wear an ID badge."',
        "options": ["have to", "has to", "must to", "should to"],
        "correct_answer": "have to",
        "points": 5,
    },
    {
        "id": 35,
        "band": 4,
        "level": "A2.4",
        "section": "curriculum",
        "type": "grammar",
        "topic": "First Conditional (If clause)",
        "question": 'Conditional condition: "If it _______ tomorrow, we will stay at home."',
        "options": ["rains", "will rain", "rained", "is raining"],
        "correct_answer": "rains",
        "points": 5,
    },
    {
        "id": 36,
        "band": 4,
        "level": "A2.4",
        "section": "curriculum",
        "type": "grammar",
        "topic": "First Conditional (Result clause)",
        "question": 'Result clause: "If you practice every day, you _______ improve quickly."',
        "options": ["will", "would", "are", "did"],
        "correct_answer": "will",
        "points": 5,
    },
    {
        "id": 37,
        "band": 4,
        "level": "A2.4",
        "section": "curriculum",
        "type": "grammar",
        "topic": "Relative Pronouns (People: Who)",
        "question": 'Relative pronoun: "The woman _______ lives next door is a software engineer."',
        "options": ["who", "which", "whose", "where"],
        "correct_answer": "who",
        "points": 5,
    },
    {
        "id": 38,
        "band": 4,
        "level": "A2.4",
        "section": "curriculum",
        "type": "grammar",
        "topic": "Relative Pronouns (Objects: Which)",
        "question": 'Relative pronoun: "This is the laptop _______ I bought yesterday."',
        "options": ["which", "who", "whom", "where"],
        "correct_answer": "which",
        "points": 5,
    },
    {
        "id": 39,
        "band": 4,
        "level": "A2.4",
        "section": "curriculum",
        "type": "vocabulary",
        "topic": "Spatial Phrasal Verbs (Take off)",
        "question": 'Select phrasal verb: "Please _______ your shoes before entering the house."',
        "options": ["take off", "turn off", "give up", "get off"],
        "correct_answer": "take off",
        "points": 5,
    },
    {
        "id": 40,
        "band": 4,
        "level": "A2.4",
        "section": "curriculum",
        "type": "vocabulary",
        "topic": "Everyday Phrasal Verbs (Turn on)",
        "question": 'Select phrasal verb: "It is very dark in here; can you _______ the lights?"',
        "options": ["turn on", "turn up", "look for", "pick out"],
        "correct_answer": "turn on",
        "points": 5,
    },

    # ─── BAND 5: B1 INICIAL (Questions 41-50) ──────────────────────────────────
    {
        "id": 41,
        "band": 5,
        "level": "B1.1",
        "section": "curriculum",
        "type": "grammar",
        "topic": "Present Perfect (Life Experience)",
        "question": 'Life experience: "Have you ever _______ Japanese food?"',
        "options": ["eaten", "ate", "eat", "eating"],
        "correct_answer": "eaten",
        "points": 5,
    },
    {
        "id": 42,
        "band": 5,
        "level": "B1.1",
        "section": "curriculum",
        "type": "grammar",
        "topic": "Present Perfect vs Past Simple",
        "question": 'Specific past time: "I _______ to London in the summer of 2021."',
        "options": ["went", "have gone", "have been", "go"],
        "correct_answer": "went",
        "points": 5,
    },
    {
        "id": 43,
        "band": 5,
        "level": "B1.1",
        "section": "curriculum",
        "type": "grammar",
        "topic": "Duration with For",
        "question": 'Duration: "She has worked as a doctor _______ five years."',
        "options": ["for", "since", "during", "ago"],
        "correct_answer": "for",
        "points": 5,
    },
    {
        "id": 44,
        "band": 5,
        "level": "B1.1",
        "section": "curriculum",
        "type": "grammar",
        "topic": "Starting point with Since",
        "question": 'Starting point: "They have lived in this apartment _______ 2018."',
        "options": ["since", "for", "from", "in"],
        "correct_answer": "since",
        "points": 5,
    },
    {
        "id": 45,
        "band": 5,
        "level": "B1.1",
        "section": "curriculum",
        "type": "grammar",
        "topic": "Present Perfect with Yet",
        "question": 'Negative expectation: "I checked my inbox, but I haven\'t received your email _______."',
        "options": ["yet", "already", "still", "just"],
        "correct_answer": "yet",
        "points": 5,
    },
    {
        "id": 46,
        "band": 5,
        "level": "B1.2",
        "section": "curriculum",
        "type": "grammar",
        "topic": "Second Conditional (Hypothetical)",
        "question": 'Hypothetical situation: "If I won a million dollars, I _______ travel around the world."',
        "options": ["would", "will", "can", "had"],
        "correct_answer": "would",
        "points": 5,
    },
    {
        "id": 47,
        "band": 5,
        "level": "B1.2",
        "section": "curriculum",
        "type": "grammar",
        "topic": "Second Conditional (Subjunctive Were)",
        "question": 'Imaginary state: "If I _______ in your position, I would decline that risky proposal."',
        "options": ["were", "was", "am", "have been"],
        "correct_answer": "were",
        "points": 5,
    },
    {
        "id": 48,
        "band": 5,
        "level": "B1.2",
        "section": "curriculum",
        "type": "grammar",
        "topic": "Passive Voice (Past Simple)",
        "question": 'Passive voice: "That famous masterpiece was _______ by Leonardo da Vinci."',
        "options": ["painted", "paint", "painting", "paints"],
        "correct_answer": "painted",
        "points": 5,
    },
    {
        "id": 49,
        "band": 5,
        "level": "B1.2",
        "section": "curriculum",
        "type": "vocabulary",
        "topic": "Cognitive Phrasal Verbs (Find out)",
        "question": 'Discover information: "We need to _______ what time the flight departs."',
        "options": ["find out", "give up", "run out", "look up"],
        "correct_answer": "find out",
        "points": 5,
    },
    {
        "id": 50,
        "band": 5,
        "level": "B1.2",
        "section": "curriculum",
        "type": "vocabulary",
        "topic": "Opinion Linking Expressions",
        "question": 'Expressing viewpoint: "_______, remote work increases productivity when managed well."',
        "options": ["In my opinion", "For my view", "According to me", "As to me"],
        "correct_answer": "In my opinion",
        "points": 5,
    },

    # ─── BAND 6: B1/B2 AVANZADO (Questions 51-60) ─────────────────────────────
    {
        "id": 51,
        "band": 6,
        "level": "B2.1",
        "section": "curriculum",
        "type": "grammar",
        "topic": "Third Conditional (Past Regret)",
        "question": 'Past regret: "If we had left ten minutes earlier, we _______ missed the train."',
        "options": ["wouldn't have", "won't have", "hadn't", "wouldn't"],
        "correct_answer": "wouldn't have",
        "points": 5,
    },
    {
        "id": 52,
        "band": 6,
        "level": "B2.1",
        "section": "curriculum",
        "type": "grammar",
        "topic": "Mixed Conditionals",
        "question": 'Past cause with present effect: "If he had accepted the promotion last year, he _______ in London today."',
        "options": ["would be", "would have been", "will be", "is"],
        "correct_answer": "would be",
        "points": 5,
    },
    {
        "id": 53,
        "band": 6,
        "level": "B2.1",
        "section": "curriculum",
        "type": "grammar",
        "topic": "Reported Speech (Tense Backshift)",
        "question": 'Reported speech: "She told me: \'I am feeling sick.\' → She told me that she _______ sick."',
        "options": ["was feeling", "is feeling", "had felt", "would feel"],
        "correct_answer": "was feeling",
        "points": 5,
    },
    {
        "id": 54,
        "band": 6,
        "level": "B2.2",
        "section": "curriculum",
        "type": "grammar",
        "topic": "Reported Questions (Word Order)",
        "question": 'Indirect question word order: "The interviewer asked me where I _______ during college."',
        "options": ["lived", "did live", "do live", "have lived"],
        "correct_answer": "lived",
        "points": 5,
    },
    {
        "id": 55,
        "band": 6,
        "level": "B2.2",
        "section": "curriculum",
        "type": "grammar",
        "topic": "Modals of Past Deduction (Must have)",
        "question": 'Logical certainty about the past: "The ground is soaking wet. It _______ rained heavily last night."',
        "options": ["must have", "should have", "could", "would have"],
        "correct_answer": "must have",
        "points": 5,
    },
    {
        "id": 56,
        "band": 6,
        "level": "B2.2",
        "section": "curriculum",
        "type": "grammar",
        "topic": "Modals of Past Regret (Should have)",
        "question": 'Criticism/regret: "I feel terrible today. I _______ eaten that entire greasy pizza."',
        "options": ["shouldn't have", "couldn't have", "must not", "wouldn't have"],
        "correct_answer": "shouldn't have",
        "points": 5,
    },
    {
        "id": 57,
        "band": 6,
        "level": "B2.3",
        "section": "curriculum",
        "type": "grammar",
        "topic": "Concession Clauses (Although)",
        "question": 'Concession clause: "_______ the weather forecast predicted heavy storms, the team went hiking."',
        "options": ["Although", "Despite", "In spite of", "However"],
        "correct_answer": "Although",
        "points": 5,
    },
    {
        "id": 58,
        "band": 6,
        "level": "B2.3",
        "section": "curriculum",
        "type": "grammar",
        "topic": "Concession Prepositions (Despite + Noun)",
        "question": 'Preposition of concession: "_______ the immense financial pressure, the startup achieved profitability."',
        "options": ["Despite", "Although", "Even though", "Whereas"],
        "correct_answer": "Despite",
        "points": 5,
    },
    {
        "id": 59,
        "band": 6,
        "level": "B2.4",
        "section": "curriculum",
        "type": "grammar",
        "topic": "Wish + Past Perfect (Past Regret)",
        "question": 'Expressing past regret: "I wish I _______ more attention during yesterday\'s crucial briefing."',
        "options": ["had paid", "paid", "would pay", "have paid"],
        "correct_answer": "had paid",
        "points": 5,
    },
    {
        "id": 60,
        "band": 6,
        "level": "B2.4",
        "section": "curriculum",
        "type": "grammar",
        "topic": "Formal Inversion (Negative Adverbials)",
        "question": 'Formal emphatic inversion: "Hardly _______ the airport when the severe gale began."',
        "options": ["had we reached", "we had reached", "did we reach", "have we reached"],
        "correct_answer": "had we reached",
        "points": 5,
    },
]


PHONETIC_QUESTIONS_20: List[Dict[str, Any]] = [
    # ─── PURE SOUND DISCRIMINATION (Questions 61-70) ──────────────────────────
    {
        "id": 61,
        "section": "phonetics",
        "type": "phonetic_sound",
        "phoneme_symbol": "/θ/",
        "audio_url": "/audio/phonemes/fricative_th_voiceless.mp3",
        "question": "Escucha el sonido del fonema y selecciona el símbolo IPA correspondiente:",
        "instruction": "Pulsa el botón de audio para escuchar el fonema aislado.",
        "options": ["/θ/", "/ð/", "/s/", "/f/"],
        "correct_answer": "/θ/",
        "points": 5,
    },
    {
        "id": 62,
        "section": "phonetics",
        "type": "phonetic_sound",
        "phoneme_symbol": "/ð/",
        "audio_url": "/audio/phonemes/fricative_th_voiced.mp3",
        "question": "Escucha el sonido del fonema y selecciona el símbolo IPA correspondiente:",
        "instruction": "Pulsa el botón de audio para escuchar el fonema aislado.",
        "options": ["/ð/", "/d/", "/z/", "/θ/"],
        "correct_answer": "/ð/",
        "points": 5,
    },
    {
        "id": 63,
        "section": "phonetics",
        "type": "phonetic_sound",
        "phoneme_symbol": "/iː/",
        "audio_url": "/audio/phonemes/vowel_long_i.mp3",
        "question": "Escucha la vocal larga y selecciona su símbolo IPA:",
        "instruction": "Pulsa el botón de audio para escuchar la vocal.",
        "options": ["/iː/", "/ɪ/", "/e/", "/eɪ/"],
        "correct_answer": "/iː/",
        "points": 5,
    },
    {
        "id": 64,
        "section": "phonetics",
        "type": "phonetic_sound",
        "phoneme_symbol": "/ɪ/",
        "audio_url": "/audio/phonemes/vowel_short_i.mp3",
        "question": "Escucha la vocal corta y relajada y selecciona su símbolo IPA:",
        "instruction": "Pulsa el botón de audio para escuchar la vocal.",
        "options": ["/ɪ/", "/iː/", "/e/", "/ə/"],
        "correct_answer": "/ɪ/",
        "points": 5,
    },
    {
        "id": 65,
        "section": "phonetics",
        "type": "phonetic_sound",
        "phoneme_symbol": "/æ/",
        "audio_url": "/audio/phonemes/vowel_short_ae.mp3",
        "question": "Escucha la vocal abierta y selecciona su símbolo IPA:",
        "instruction": "Pulsa el botón de audio para escuchar la vocal.",
        "options": ["/æ/", "/ʌ/", "/ɑː/", "/e/"],
        "correct_answer": "/æ/",
        "points": 5,
    },
    {
        "id": 66,
        "section": "phonetics",
        "type": "phonetic_sound",
        "phoneme_symbol": "/ʃ/",
        "audio_url": "/audio/phonemes/fricative_sh.mp3",
        "question": "Escucha la consonante fricativa y selecciona su símbolo IPA:",
        "instruction": "Pulsa el botón de audio para escuchar la consonante.",
        "options": ["/ʃ/", "/tʃ/", "/s/", "/ʒ/"],
        "correct_answer": "/ʃ/",
        "points": 5,
    },
    {
        "id": 67,
        "section": "phonetics",
        "type": "phonetic_sound",
        "phoneme_symbol": "/tʃ/",
        "audio_url": "/audio/phonemes/affricate_ch.mp3",
        "question": "Escucha la consonante africada y selecciona su símbolo IPA:",
        "instruction": "Pulsa el botón de audio para escuchar la consonante.",
        "options": ["/tʃ/", "/ʃ/", "/dʒ/", "/t/"],
        "correct_answer": "/tʃ/",
        "points": 5,
    },
    {
        "id": 68,
        "section": "phonetics",
        "type": "phonetic_sound",
        "phoneme_symbol": "/dʒ/",
        "audio_url": "/audio/phonemes/affricate_j.mp3",
        "question": "Escucha la consonante africada sonora y selecciona su símbolo IPA:",
        "instruction": "Pulsa el botón de audio para escuchar la consonante.",
        "options": ["/dʒ/", "/j/", "/tʃ/", "/ʒ/"],
        "correct_answer": "/dʒ/",
        "points": 5,
    },
    {
        "id": 69,
        "section": "phonetics",
        "type": "phonetic_sound",
        "phoneme_symbol": "/ŋ/",
        "audio_url": "/audio/phonemes/nasal_ng.mp3",
        "question": "Escucha la consonante nasal velar y selecciona su símbolo IPA:",
        "instruction": "Pulsa el botón de audio para escuchar la consonante.",
        "options": ["/ŋ/", "/n/", "/m/", "/g/"],
        "correct_answer": "/ŋ/",
        "points": 5,
    },
    {
        "id": 70,
        "section": "phonetics",
        "type": "phonetic_sound",
        "phoneme_symbol": "/ə/",
        "audio_url": "/audio/phonemes/vowel_schwa.mp3",
        "question": "Escucha el sonido neutro (Schwa) y selecciona su símbolo IPA:",
        "instruction": "Pulsa el botón de audio para escuchar el sonido.",
        "options": ["/ə/", "/ʌ/", "/ɜː/", "/e/"],
        "correct_answer": "/ə/",
        "points": 5,
    },

    # ─── HIGHLIGHTED WORD-PHONEME MAPPING (Questions 71-80) ───────────────────
    {
        "id": 71,
        "section": "phonetics",
        "type": "phonetic_word",
        "target_word": "think",
        "highlight_part": "th",
        "phoneme_symbol": "/θ/",
        "question": "¿Qué sonido fonético IPA representa la sección resaltada en la palabra 'think'?",
        "instruction": "Presiona la palabra para escucharla y observa las letras resaltadas.",
        "options": ["/θ/", "/ð/", "/t/", "/s/"],
        "correct_answer": "/θ/",
        "points": 5,
    },
    {
        "id": 72,
        "section": "phonetics",
        "type": "phonetic_word",
        "target_word": "this",
        "highlight_part": "th",
        "phoneme_symbol": "/ð/",
        "question": "¿Qué sonido fonético IPA representa la sección resaltada en la palabra 'this'?",
        "instruction": "Presiona la palabra para escucharla y observa las letras resaltadas.",
        "options": ["/ð/", "/θ/", "/d/", "/z/"],
        "correct_answer": "/ð/",
        "points": 5,
    },
    {
        "id": 73,
        "section": "phonetics",
        "type": "phonetic_word",
        "target_word": "sheep",
        "highlight_part": "ee",
        "phoneme_symbol": "/iː/",
        "question": "¿Qué sonido fonético IPA representa la sección resaltada en la palabra 'sheep'?",
        "instruction": "Presiona la palabra para escucharla y observa las letras resaltadas.",
        "options": ["/iː/", "/ɪ/", "/e/", "/eɪ/"],
        "correct_answer": "/iː/",
        "points": 5,
    },
    {
        "id": 74,
        "section": "phonetics",
        "type": "phonetic_word",
        "target_word": "ship",
        "highlight_part": "i",
        "phoneme_symbol": "/ɪ/",
        "question": "¿Qué sonido fonético IPA representa la sección resaltada en la palabra 'ship'?",
        "instruction": "Presiona la palabra para escucharla y observa las letras resaltadas.",
        "options": ["/ɪ/", "/iː/", "/e/", "/aɪ/"],
        "correct_answer": "/ɪ/",
        "points": 5,
    },
    {
        "id": 75,
        "section": "phonetics",
        "type": "phonetic_word",
        "target_word": "cat",
        "highlight_part": "a",
        "phoneme_symbol": "/æ/",
        "question": "¿Qué sonido fonético IPA representa la sección resaltada en la palabra 'cat'?",
        "instruction": "Presiona la palabra para escucharla y observa las letras resaltadas.",
        "options": ["/æ/", "/ʌ/", "/ɑː/", "/e/"],
        "correct_answer": "/æ/",
        "points": 5,
    },
    {
        "id": 76,
        "section": "phonetics",
        "type": "phonetic_word",
        "target_word": "shoe",
        "highlight_part": "sh",
        "phoneme_symbol": "/ʃ/",
        "question": "¿Qué sonido fonético IPA representa la sección resaltada en la palabra 'shoe'?",
        "instruction": "Presiona la palabra para escucharla y observa las letras resaltadas.",
        "options": ["/ʃ/", "/tʃ/", "/s/", "/ʒ/"],
        "correct_answer": "/ʃ/",
        "points": 5,
    },
    {
        "id": 77,
        "section": "phonetics",
        "type": "phonetic_word",
        "target_word": "chair",
        "highlight_part": "ch",
        "phoneme_symbol": "/tʃ/",
        "question": "¿Qué sonido fonético IPA representa la sección resaltada en la palabra 'chair'?",
        "instruction": "Presiona la palabra para escucharla y observa las letras resaltadas.",
        "options": ["/tʃ/", "/ʃ/", "/k/", "/dʒ/"],
        "correct_answer": "/tʃ/",
        "points": 5,
    },
    {
        "id": 78,
        "section": "phonetics",
        "type": "phonetic_word",
        "target_word": "vision",
        "highlight_part": "s",
        "phoneme_symbol": "/ʒ/",
        "question": "¿Qué sonido fonético IPA representa la sección resaltada en la palabra 'vision'?",
        "instruction": "Presiona la palabra para escucharla y observa las letras resaltadas.",
        "options": ["/ʒ/", "/ʃ/", "/z/", "/dʒ/"],
        "correct_answer": "/ʒ/",
        "points": 5,
    },
    {
        "id": 79,
        "section": "phonetics",
        "type": "phonetic_word",
        "target_word": "judge",
        "highlight_part": "dg",
        "phoneme_symbol": "/dʒ/",
        "question": "¿Qué sonido fonético IPA representa la sección resaltada en la palabra 'judge'?",
        "instruction": "Presiona la palabra para escucharla y observa las letras resaltadas.",
        "options": ["/dʒ/", "/tʃ/", "/g/", "/j/"],
        "correct_answer": "/dʒ/",
        "points": 5,
    },
    {
        "id": 80,
        "section": "phonetics",
        "type": "phonetic_word",
        "target_word": "sing",
        "highlight_part": "ng",
        "phoneme_symbol": "/ŋ/",
        "question": "¿Qué sonido fonético IPA representa la sección resaltada en la palabra 'sing'?",
        "instruction": "Presiona la palabra para escucharla y observa las letras resaltadas.",
        "options": ["/ŋ/", "/n/", "/g/", "/nk/"],
        "correct_answer": "/ŋ/",
        "points": 5,
    },
]


def get_all_diagnosis_questions() -> List[Dict[str, Any]]:
    """Return all 80 calibrated questions (60 curricular + 20 phonetic)."""
    return CURRICULAR_QUESTIONS_60 + PHONETIC_QUESTIONS_20
